#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00
#PBS -l vmem=30gb

singularity exec -e docker://brainlife/mcr:r2019a ./compiled/mergeTCK

matlab -nosplash -nodisplay -r mergeTCK
if [ ! -f ./output/track.tck ]; then
       echo "mergeTCK didn't produce track.tck"
       exit 1
fi

echo "all done"
